### ISSUE TITLE
CardNumberExtension problem (NULL everywhere)

### ISSUE THREAD

**Issue by kimlada** [ondrakoupil/csob#18]
Hi Ondra,

I use your library for my one project and the library works like a charm with one exception -> extensions.

I wanted to use CardNumberExtension to get masked card number of user for one click payment but I have always gotten NULL from methods: 

getResponseData()
getMaskedCln()
getExpiration()

and so on.

Test code:
```
	$payment = new Payment($id, null, $user);
	$payment->setOneClickPayment(true);
	$payment->addCartItem("지불", 1, 1 * 100);
	$cardExtension = new CardNumberExtension();

	$client->paymentInit($payment, $cardExtension);

	$payId = $payment->getPayId();
	$client->paymentStatus($payId, true, $cardExtension);

	var_dump($cardExtension->getLongMaskedCln()); // NULL
	var_dump($cardExtension->getResponseData()); // NULL
	var_dump($cardExtension->getMaskedCln()); // NULL
	var_dump($cardExtension->getExpiration()); // NULL
```

What am i doing wrong?

Best Regards
김라댜

**Comment by ondrakoupil** [comment]
Hi, 

have you activated the extension "maskClnRP " in settings in the bank? The extensions are not allowed by default, you need to activate it. Since you are receiving correct answer from bank, it is not a problem of signing or calling the API method.

Also, as far as I know, this extension is supposed to be used with payment/status method, not payment/init. 
See https://github.com/csob/paymentgateway/wiki/eAPI-v1.6-mask-cln  or example in https://github.com/ondrakoupil/csob/blob/master/README.md#cardnumberextension (it is only in czech readme.md, I need to update the english version, sorry).
It works only with one-click payments. That basically means that when paying for the first time using payment/init, the payment is saved as some kind of template, a pre-authorization for similar payments in the future. Later, you can use payment/oneclick/* methods to redo that payment. It is useful for repeating subscriptions, charging monthly fees etc. And for these re-done payments, this extension can be used. Not for regular payments.

If everything else fails, please can you attach detailed log of the communication between your server and bank API? See https://github.com/ondrakoupil/csob/blob/master/README.en.md#logging for more info about how to set it up.

Ondra
